### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by santiagogabrielcastillo**
Adds categories with their images to the homepage. Each image works as a link to the categories#show method, where you can see every provider for each category. For that, it also adds the categories controller, show method and the show view.

Here it's what it looks like:

image

### CODE REVIEW

**Comment by santiagogabrielcastillo** [comment]
Screenshot of categories#show: 

image

**Review by jpbalarini — CHANGES_REQUESTED** [review]
Let's make it look more like on the designs

**Comment by santiagogabrielcastillo** [comment]
Don't know what design to follow in this view! I think there is no screenshot of the categories' providers

**Comment by santiagogabrielcastillo** [comment]
This is the result with the updates:

image

**Comment by santiagogabrielcastillo** [comment]
Fixing the spacing and font-size issues: 

image

**Review by jpbalarini — APPROVED** [review]
Now it looks much more like the designs 💪 
Awesome work!

**Pull request merged**
